### ISSUE TITLE
version is not defined

### ISSUE THREAD

**Issue by arieljannai** [jhaker/nodejs-msbuild#10]
I get a `version is not defined` error when trying to build.
I'm using it right now as simple as possible by the example in the readme page:
```js
var _msbuild = require('msbuild');
var msbuild = new _msbuild(); 
msbuild.sourcePath = 'c:/your_app.sln';
msbuild.build();
```

I checked a bit, and the `validFrameworkDir` in `getFrameworkDirectories` is not returning any folder. The folders I have under `C:\Program Files (x86)\MSBuild` are:
* 4.0
* Microsoft
* Microsoft.Cpp

and none of them has an `indexOf('1')`

I've tried setting the `msbuild.version` with the version of .net (4.0 or full one 4.0.something), with and without the `v` and also the msbuild version. None of them helped.

Also, to which `version` variable [this line refers to](https://github.com/jhaker/nodejs-msbuild/blob/master/msbuild.js#L126)?
It seems to be global, but I guess it should've been set as `var` before that, or using `this.version` which also exists.

**Comment by matneyx** [comment]
I believe you need to push a new version to the overrideParams, like so:
`msbuild.overrideParams.push('/tv:14.0');`

**Comment by arieljannai** [comment]
Thanks, I haven't tried the vs version, I'll try it next week.

**Comment by arieljannai** [comment]
@matneyx It didn't helped, any idea?

**Comment by arieljannai** [comment]
Ok, I had a problem with msbuild.exe which disappeared.
Maybe it's better to have another error message so it will be more understandable.

**Comment by jhaker** [comment]
I like that idea of extending the error messages. I'm closing this out as an issue but will be adding it to the future enhancement list.

**Comment by arieljannai** [comment]
Great :sunglasses:
