### ISSUE TITLE
Path to msbuild cannot be determined properly when Visual Studio 15 is installed

### ISSUE THREAD

**Issue by sandord** [jhaker/nodejs-msbuild#12]
events.js:141
		  throw er; // Unhandled 'error' event
		  ^

	Error: spawn C:\WINDOWS\microsoft.net\Framework64\vundefined\msbuild.exe ENOENT
		at exports._errnoException (util.js:873:11)
		at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
		at onErrorNT (internal/child_process.js:344:16)
		at nextTickCallbackWith2Args (node.js:442:9)
		at process._tickCallback (node.js:356:17)
		at Function.Module.runMain (module.js:443:11)
		at startup (node.js:139:18)
		at node.js:968:3

**Comment by sandord** [comment]
This issue is caused by the false assumption that all versions of msbuild have a `bin/msbuild.exe` file. The version of msbuild that comes with Visual Studio 15 (=2017) clearly doesn't have `bin/msbuild.exe` file. Actually, it is nowhere to be found within the `msbuild` folder.

**Comment by jhaker** [comment]
I would recommend dotnet for 2017 https://www.npmjs.com/package/dotnet. 

If you want to use msbuild you can either update the config $(MSBuildToolsPath), override the msbuild.buildexe or update the registry. 


<msbuildToolsets default="12.0">  
   <toolset toolsVersion="12.0">  
      <property name="MSBuildToolsPath"   
        value="C:\SpecialPath" />  
   </toolset>  
</msbuildToolsets>


msbuild.buildexe = function(){
	return 'C:\\Program Files (x86)\\MSBuild\\12.0\\Bin\\msbuild.exe'
}

\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\MSBuild\ToolsVersions

**Comment by jhaker** [comment]
No change. Provided recommendation.
