### ISSUE TITLE
Building does not work with Visual Studio 2017

### ISSUE THREAD

**Issue by dittodhole** [jhaker/nodejs-msbuild#16]
I use the following `.js`-file to build my solution:

```js
"use strict";

const _msbuild = require("msbuild");
const msbuild = new _msbuild();

msbuild.sourcePath = "somesolution.sln";
msbuild.processor = "AnyCPU";
msbuild.configuration = "Release";
msbuild.overrideParams.push("/clp:ErrorsOnly");

msbuild.build();
```

This gives me the following output with Visual Studio 2017 installed:

```txt
  build starting
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\WINDOWS\microsoft.net\Framework\vundefined\msbuild.exe ENOENT
    at exports._errnoException (util.js:1034:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)
    at bootstrap_node.js:538:3
```

**Comment by zszep** [comment]
I'm getting exactly the same error. After upgrading to Visual Studio 2017, msbuild isn't working any more. Any solution?

**Comment by zszep** [comment]
Is this project still active? Nobody seems to be doing anything about this. VS 2017 is out for quite a while now.

**Comment by jhaker** [comment]
This issue has been resolved. I tested after installing vs 2017 professional using nodejs-msbuild-examples.

**Comment by jvopalensky** [comment]
Is this completely fixed? 

I no longer see the "spawn C:\WINDOWS\microsoft.net\Framework\vundefined\msbuild.exe ENOENT" error. However, now I see my msbuild override '/p:VisualStudioVersion=15.0' is not honored. It is not using the MSBuild.exe in "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\" folder as I would expect. I see it still uses "C:\Program Files (x86)\MSBuild\14.0\bin\amd64\msbuild.exe".

```
Previewing MSBUILD Command
********** test - start ************
MS build command: C:\Program Files (x86)\MSBuild\14.0\bin\amd64\msbuild.exe
MS build params:
[ 'C:\\Projects\\FirmwaterLMS',
  '/p:configuration=Release',
  '/p:VisualStudioVersion=15.0',
  '/p:RunCodeAnalysis=false',
  '/toolsversion:14.0',
  '/target:rebuild',
  '/maxcpucount',
  '/consoleloggerparameters:Summary',
  '/verbosity:minimal' ]
********** test - end  ************
```

**Comment by jvopalensky** [comment]
Actually after installing VS2017 web development build tools (from https://www.visualstudio.com/thank-you-downloading-visual-studio/?sku=BuildTools&rel=15) I see that the VS2017 MSBuild.exe is installed by default in the "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\" folder.
