### ISSUE TITLE
Use the correct mbsuild-path for .NET 4.0 when .NET 4.5 is installed as well

### ISSUE THREAD

**Issue by dittodhole** [jhaker/nodejs-msbuild#20]
We run a build on our server, which has following components installed:

- Microsoft .NET Framework 4.5 Multi-Targeting Pack
- Microsoft .NET Framework 4.5.1 Multi-Targeting Pack
- Microsoft .NET Framework 4.5.2 Multi-Targeting Pack
- Microsoft Visual Studio 2015 Community 2015 with Update 2

Building .NET 4.0 projects from within Visual Studio correctly utilizes msbuild from the correct Multi-Targeting Pack under `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe`.

Whereas _nodsjs-msbuild_ uses `C:\Windows\microsoft.net\Framework\v4.0.30319\msbuild.exe` (which internally is 4.5).

This becomes a problem with `System.Runtime.CompilerServices.ExtensionAttribute, System.Core` (see https://stackoverflow.com/a/13750130 for more information) which was moved to `mscorlib`.

**Comment by jhaker** [comment]
Updated pull request #24. Closing as complete.
