### ISSUE TITLE
Using vs 2015 MSBuild

### ISSUE THREAD

**Issue by glaidler** [jhaker/nodejs-msbuild#4]
Hi, is there any plans to extend to support MSBuild as supplied with VS 2015?  This is in c:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe

**Comment by jhaker** [comment]
Good quesiton. You should be able to use the override params to specify VS 2015. I added an example on the readme file. Try it out and let me know if it works. 

Look for the following...

//VisualStudioVersion=14.0 => C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0
overrideParams.push('/p:VisualStudioVersion=14.0');
