### ISSUE TITLE
Building non .sln files

### ISSUE THREAD

**Issue by RedmonkeyDF** [jhaker/nodejs-msbuild#6]
Hi there.  I use this to build projects that do not have a .sln extension.  I have to patch the package to check for my extension when I install it each time.  Is there any way you can make the routine that checks for valid projects check against a configurable property of the msbuild object?

**Comment by RedmonkeyDF** [comment]
Hey there

Started working on it, it is real simple.  I will issue a pull request once I am done.

S

**Comment by jhaker** [comment]
After further review I found the two file extension checks unnecessarily restrictive. I believe the removal of the restrictions should have the same affect as your proposed changes. For this reason I will go ahead and close out the issue as completed.

**Comment by RedmonkeyDF** [comment]
Yessir. My attempt was just a kludge around that. Removing them would be perfect. Thanks. 

S
