### ISSUE TITLE
this.logger is not a function

### ISSUE THREAD

**Issue by narg95** [jhaker/nodejs-msbuild#8]
Hello,

I am using the publish functionality but I get the following error, could you please help me to solve the issue?

C:\Sources\rs\rs.backend\node_modules\msbuild\msbuild.js:351
        this.exec(this.buildexe(),params,function(){this.logger('publish done');});
                                                         ^

TypeError: this.logger is not a function
    at C:\Sources\rs\rs.backend\node_modules\msbuild\msbuild.js:351:51
    at ChildProcess.onClose (C:\Sources\rs\rs.backend\node_modules\msbuild\msbuild.js:200:3)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:827:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

The code I am using is simple:

var Msbuild = require('msbuild');
var msbuild = new Msbuild(); 
msbuild.sourcePath = `my solution file.sln`;
msbuild.build();

msbuild = new Msbuild();
msbuild.sourcePath = 'my project file.csproj';
msbuild.publish();

**Comment by narg95** [comment]
I create a pull request to solve the problem, please take a look ! :)

**Comment by jhaker** [comment]
Nice work. Thanks for the update.
